FoodBank/objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Expense__c</fullName>
        <label>Expense</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/objects/Family__c.object
<CustomObject>
    <description>Our families</description>
    <label>Family</label>
    <nameField>
        <label>FamilyName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FoodBank/objects/GroupService__c.object
<CustomObject>
    <description>A meal service provided to a group of people. At present this is only a group meal.</description>
    <fields>
        <fullName>Family__c</fullName>
        <description>The group to which this service was provided</description>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Group Services</relationshipLabel>
        <relationshipName>GroupServices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Group Service</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/objects/Income__c.object
<CustomObject>
    <description>Family income information</description>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Incomes</relationshipLabel>
        <relationshipName>Incomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Income</label>
    <nameField>
        <label>Income Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/objects/Note__c.object
<CustomObject>
    <description>Family notes</description>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <label>Note</label>
    <nameField>
        <label>Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/objects/Person__c.object
<CustomObject>
    <description>Family/Group members</description>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/objects/Phone__c.object
<CustomObject>
    <description>A family telephone number</description>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Phones</relationshipLabel>
        <relationshipName>Phones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Phone</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/objects/Service__c.object
<CustomObject>
    <description>A service provided to a family</description>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/objects/TimeSlot__c.object
<CustomObject>
    <label>TimeSlot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TimeSlots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FoodBank/objects/Verification__c.object
<CustomObject>
    <description>Verifications</description>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Verifications</relationshipLabel>
        <relationshipName>Verifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Verification</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/classes/DataDeleter.cls
global class DataDeleter {
    
    private Integer currentQueryIdx = -1;
    private String[] deleteQeries = new List<String> {
        'SELECT Id FROM Person__c',
        'SELECT Id FROM Income__c',
        'SELECT Id FROM Expense__c',
        'SELECT Id FROM Verification__c',
        'SELECT Id FROM Phone__c',
        'SELECT Id FROM Note__c',
        'SELECT Id FROM Service__c',
        'SELECT Id FROM GroupService__c',
        'SELECT Id FROM TimeSlot__c',
        'SELECT Id FROM Family__c'
    };
    
    void startNextBatch() {
        currentQueryIdx += 1;
        if (currentQueryIdx >= deleteQeries.size()) {
            System.debug('All objects have been deleted');
            return;
        }
        BatchDelete BDel = new BatchDelete(this);
        BDel.query = deleteQeries[currentQueryIdx];
        ID batchProcessId = Database.executeBatch(BDel);
        System.debug('Started batch process ID: ' + batchProcessId);
    }
    
    public void deleteAllData() {
        startNextBatch();
    }
    
    public void batchFinished(BatchDelete batch) {
        System.debug('Batch finished: ' + batch.query);
    }
}