FoodBank/objects/Family__c.object
<CustomObject>
    <description>Our families</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Family</label>
    <nameField>
        <label>FamilyName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FoodBank/objects/Person__c.object
<CustomObject>
    <description>Family/Group members</description>
    <fields>
        <fullName>Age__c</fullName>
        <description>The person&apos;s age</description>
        <formula>YEAR(DATEVALUE(NOW()))-YEAR( DOB__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <description>Date of birth</description>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <label>Relationship</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/objects/Phone__c.object
<CustomObject>
    <description>A family telephone number</description>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Phones</relationshipLabel>
        <relationshipName>Phones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Phone</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/objects/Service__c.object
<CustomObject>
    <description>A service provided to a family</description>
    <fields>
        <fullName>DateOfService__c</fullName>
        <description>When was the service provided/delivered?</description>
        <label>Date of Service</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/classes/BirthdayListController.cls
public class BirthdayListController {

    private class BirthdayInfo {
        public String     name {get; set;}
        public Date       dob {get; set;}
        public Decimal    age {get; set;}
        public String     gender {get; set;}
        public String     file_no {get; set;}
        public String     relation {get; set;}
        public Date       last_service {get; set;}
        public String     phone {get; set;}
    }

    public Date service_start_date { get; set; }
    public Date service_end_date { get; set; }
    public Integer birthday_month { get; set; }
    
    public Boolean show_header { get; set; }
    public String render_as { get; set; }
    
    public List<BirthdayInfo> birthdays { get; set; }

    private void getReportData() {
        AggregateResult[] families_served = [SELECT Family__r.id FROM Service__c WHERE DateOfService__c >= :service_start_date AND DateOfService__c < :service_end_date GROUP BY Family__r.id];
        List<Id> family_ids = new List<Id>();
        for (AggregateResult ar : families_served) {
            family_ids.add(ar.id);
        }
        
        // File home phone's for the families
        Map<String, String> family_phones = new Map<String, String>();
        Phone__c[] phones = [SELECT Number__c,Type__c,Family__r.ID FROM Phone__c WHERE Family__r.id in :family_ids];
        for (Phone__c phone : phones) {
            if (phone.Type__c != null && phone.Type__c.equals('Home')) {
                family_phones.put(phone.Family__r.ID, phone.Number__c);
            }
        }
        
        Person__c[] people_served = [SELECT Gender__c,Age__c,DOB__c,Relationship__c,LastName__c,Family__r.ID FROM Person__c WHERE Family__r.id in :family_ids];
        
        for (Person__c person : people_served) {
            if (person.Age__c >= 4 && person.Age__c <= 14 && person.DOB__c != null && person.DOB__c.month() == birthday_month) {
                BirthdayInfo birthday = new BirthdayInfo();
                birthday.name = person.LastName__c;
                birthday.dob = person.DOB__c;
                birthday.age = person.Age__c;
                birthday.gender = person.Gender__c;
                birthday.relation = person.Relationship__c;
                birthday.phone = family_phones.get(person.Family__r.ID);
                birthdays.add(birthday);
            }
        }
    }
    
    // Dummy action to refresh the page.
    public PageReference makePrintable() {
        return null;
    }
    
    public String month {
        get {
            Date d = Date.newInstance(2000, birthday_month, 1);
            DateTime dt = DateTime.newInstance(d, Time.newInstance(0, 0, 0, 0));
            return dt.format('MMMMM');
        }
    }
    
    public BirthdayListController() {
        
        birthdays = new List<BirthdayInfo>();

        show_header = true;
        render_as = '';
        
        service_end_date = Date.today();
        service_start_date = service_end_date;
        service_start_date = service_start_date.addYears(-1);
        birthday_month = 4;
        
        getReportData();
    }
}