FoodBank/objects/Family__c.object
<CustomObject>
    <description>Our families</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Family</label>
    <nameField>
        <label>FamilyName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FoodBank/objects/Service__c.object
<CustomObject>
    <description>A service provided to a family</description>
    <fields>
        <fullName>Adopted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Adopted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BoxSize__c</fullName>
        <label>Box Size</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S/NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S/WC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XXL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BoxType__c</fullName>
        <label>Box Type</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Supplement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compl/Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eggs only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EHP Adpt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Harvest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pack the Bag</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Produce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sandwhiches</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Snacks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youth Summer Feeding Program</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DateOfService__c</fullName>
        <description>When was the service provided/delivered?</description>
        <label>Date of Service</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DistributionMethod__c</fullName>
        <label>Distribution Method</label>
        <picklist>
            <picklistValues>
                <fullName>Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mailed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pickup</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TypeOfMeat__c</fullName>
        <label>Type of meat</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Turkey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chicken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turkey/Ham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ham/Chicken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/classes/ServiceHistoryController.cls
public class ServiceHistoryController{

  public Date start_date { get; set;}
  public Date end_date { get; set;}
  
  public boolean show_header {get; set;}
  public List<Service__c> services {get; set;}

  private void getReportData() {
    services = [SELECT id, BoxType__c, BoxSize__c, TypeOfMeat__c, Adopted__c, Family__r.Name, Type__c, DateOfService__c, DistributionMethod__c, TimeSlot__r.DateTime__c
        FROM Service__c
        WHERE DateOfService__c >= :start_date AND DateOfService__c < :end_date];
  }
  
  public ServiceHistoryController() {
    Map<String, String> params = ApexPages.currentPage().getParameters();
    end_date = params.containsKey('end_date') ? Date.parse(params.get('end_date')) : Date.today();
    start_date = params.containsKey('start_date') ? Date.parse(params.get('start_date')) : end_date.addYears(-1);
    show_header = true;
    getReportData();
  }
  
  // Dummy action to refresh the page.
  public PageReference makePrintable() {
    return null;
  }
}