FoodBank/objects/Family__c.object
<CustomObject>
    <description>Our families</description>
    <label>Family</label>
    <nameField>
        <label>FamilyName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FoodBank/objects/Service__c.object
<CustomObject>
    <description>A service provided to a family</description>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/objects/TimeSlot__c.object
<CustomObject>
    <fields>
        <fullName>Allocated__c</fullName>
        <description>The number of slots already allocated (scheduled) for various services.</description>
        <inlineHelpText>This field is automatically calculated.</inlineHelpText>
        <label>Allocated</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DateTime__c</fullName>
        <description>The date &amp; time of this time slot. If this slot is for the entire day then make the time midnight.</description>
        <label>Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Free__c</fullName>
        <formula>NumSlots__c - Allocated__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Free</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NumSlots__c</fullName>
        <defaultValue>20</defaultValue>
        <description>The number of allocated slots in this time period. This is not the number of used or available slots, and does not change when services are scheduled in this time slot.</description>
        <label>Number of Slots</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>TimeSlot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TimeSlots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FoodBank/classes/TimeSlotTriggerTest.cls
@isTest
private class TimeSlotTriggerTest{
  static testMethod void testAddRemoveTimeSlotRef(){		

    Family__c family = new Family__c(Name='TimeSlotFam1');
    insert family;

    TimeSlot__c timeslotA = new TimeSlot__c(Name='XXX',
                        DateTime__c=DateTime.parse('10/14/2014 2:00 PM'),
                        NumSlots__c=15);
    insert timeslotA;

    TimeSlot__c timeslotB = new TimeSlot__c(Name='XXX',
                        DateTime__c=DateTime.parse('10/14/2014 3:00 PM'),
                        NumSlots__c=25);
    insert timeslotB;

    // Verify that the initial state is as expected.
    timeslotA = [SELECT Allocated__c,NumSlots__c,Free__c
         FROM TimeSlot__c
         WHERE Id = :timeslotA.Id];
    System.assertEquals(null, timeslotA.Allocated__c);
    System.assertEquals(15, timeslotA.NumSlots__c);
    System.assertEquals(15, timeslotA.Free__c);

    timeslotB = [SELECT Allocated__c,NumSlots__c,Free__c
         FROM TimeSlot__c
         WHERE Id = :timeslotB.Id];
    System.assertEquals(null, timeslotB.Allocated__c);
    System.assertEquals(25, timeslotB.NumSlots__c);
    System.assertEquals(25, timeslotB.Free__c);

    Service__c service = new Service__c(TimeSlot__c=timeslotA.Id,
                                          Family__c=family.Id);

    // Cause the Trigger to execute.
    insert service;

    // Verify that the results are as expected.
    timeslotA = [SELECT Allocated__c,NumSlots__c,Free__c
         FROM TimeSlot__c
         WHERE Id = :timeslotA.Id];
    System.assertEquals(1, timeslotA.Allocated__c);
    System.assertEquals(15, timeslotA.NumSlots__c);
    System.assertEquals(14, timeslotA.Free__c);

    timeslotB = [SELECT Allocated__c,NumSlots__c,Free__c
         FROM TimeSlot__c
         WHERE Id = :timeslotB.Id];
    System.assertEquals(null, timeslotB.Allocated__c);
    System.assertEquals(25, timeslotB.NumSlots__c);
    System.assertEquals(25, timeslotB.Free__c);

    // And deleting the service should decrement the value.
    delete service;

    if (false) {
        // Verify that the results are as expected.
        timeslotA = [SELECT Allocated__c,NumSlots__c,Free__c
             FROM TimeSlot__c
             WHERE Id = :timeslotA.Id];
        System.assertEquals(0, timeslotA.Allocated__c);
        System.assertEquals(15, timeslotA.NumSlots__c);
        System.assertEquals(14, timeslotA.Free__c);
    }

    // Undeleting should increment again.
    undelete service;

    // Verify that the results are as expected.
    timeslotA = [SELECT Allocated__c,NumSlots__c,Free__c
         FROM TimeSlot__c
         WHERE Id = :timeslotA.Id];
    System.assertEquals(1, timeslotA.Allocated__c);
    System.assertEquals(15, timeslotA.NumSlots__c);
    System.assertEquals(14, timeslotA.Free__c);

    // Now switch from "A" to "B" and verify both timeslots
    service.TimeSlot__c = timeslotB.Id;
    update service; // execute trigger

    timeslotB = [SELECT Allocated__c,NumSlots__c,Free__c
         FROM TimeSlot__c
         WHERE Id = :timeslotB.Id];
    System.assertEquals(1, timeslotB.Allocated__c);
    System.assertEquals(25, timeslotB.NumSlots__c);
    System.assertEquals(24, timeslotB.Free__c);

    if (false) {
        timeslotA = [SELECT Allocated__c,NumSlots__c,Free__c
             FROM TimeSlot__c
             WHERE Id = :timeslotA.Id];
        System.assertEquals(0, timeslotA.Allocated__c);
        System.assertEquals(15, timeslotA.NumSlots__c);
        System.assertEquals(15, timeslotA.Free__c);
    }
  }
}