FoodBank/objects/Family__c.object
<CustomObject>
    <description>Our families</description>
    <label>Family</label>
    <nameField>
        <label>FamilyName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FoodBank/objects/Person__c.object
<CustomObject>
    <description>Family/Group members</description>
    <fields>
        <fullName>DOB__c</fullName>
        <description>Date of birth</description>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/objects/Service__c.object
<CustomObject>
    <description>A service provided to a family</description>
    <fields>
        <fullName>DateOfService__c</fullName>
        <description>When was the service provided/delivered?</description>
        <label>Date of Service</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/classes/DemographicsControllerTestClass.cls
@isTest 
private class DemographicsControllerTestClass {
    static testMethod void testDefaultConstructor() {
        Family__c family = new Family__c();
        insert family;

        Service__c service = new Service__c(Family__c = family.id,  DateOfService__c = Date.today() - 1);
        insert service;

        // Add male youth person
        Person__c p1 = new Person__c(Family__c = family.id, DOB__c = Date.today().addYears(-13), Gender__c = 'Male');
        insert p1;
        
        // Add female elderly person
        Person__c p2 = new Person__c(Family__c = family.id, DOB__c = Date.today().addYears(-66), Gender__c = 'Female');
        insert p2;
        
        // Add blank person
        Person__c p3 = new Person__c(Family__c = family.id);
        insert p3;

        DemographicsController controller = new DemographicsController();
    }
}