FoodBank/objects/Family__c.object
<CustomObject>
    <description>Our families</description>
    <label>Family</label>
    <nameField>
        <label>FamilyName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FoodBank/objects/Person__c.object
<CustomObject>
    <description>Family/Group members</description>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/classes/PersonNameTriggerTest.cls
@isTest
private class PersonNameTriggerTest{
  static testMethod void testUpdatePersonName(){

    Family__c family = new Family__c(Name='PersonFam1');
    insert family;

    Person__c person = new Person__c(Family__c=family.Id,
                                    FirstName__c='Joe',
                                    LastName__c='Smith');

    // Cause the Trigger to execute.
    insert person;

    // Verify that the results are as expected.
    person = [SELECT Name
         FROM Person__c
         WHERE Family__c = :family.Id];
    System.assertEquals('Smith, Joe', person.Name);

    delete person;
  }

  static testMethod void testNullNames(){

    Family__c family = new Family__c(Name='PersonFam1');
    insert family;

    Person__c person = new Person__c(Family__c=family.Id,
                                    FirstName__c=null,
                                    LastName__c='Smith');

    insert person;

    person = [SELECT Name
         FROM Person__c
         WHERE Family__c = :family.Id];
    System.assertEquals('Smith, <unknown>', person.Name);
    delete person;

    person = new Person__c(Family__c=family.Id,
                                    FirstName__c='Joe',
                                    LastName__c=null);

    insert person;

    // Verify that the results are as expected.
    person = [SELECT Name
         FROM Person__c
         WHERE Family__c = :family.Id];
    System.assertEquals('<unknown>, Joe', person.Name);
    delete person;

    person = new Person__c(Family__c=family.Id,
                                    FirstName__c=null,
                                    LastName__c=null);

    insert person;

    // Verify that the results are as expected.
    person = [SELECT Name
         FROM Person__c
         WHERE Family__c = :family.Id];
    System.assertEquals('<unknown>', person.Name);
    delete person;
  }
}