FoodBank/objects/Family__c.object
<CustomObject>
    <description>Our families</description>
    <fields>
        <fullName>AddressCombined__c</fullName>
        <description>The combined address of the family</description>
        <formula>IF(ISBLANK(AptNum__c), 
StreetNum__c &amp; &quot; &quot; &amp; StreetName__c &amp; &quot;, &quot; &amp; City__c &amp; &quot;, &quot; &amp; TEXT(State__c) &amp; &quot; &quot; &amp; Zip__c,
StreetNum__c &amp; &quot; &quot; &amp; StreetName__c &amp; &quot; Apt #&quot; &amp; AptNum__c &amp; &quot;, &quot; &amp; City__c &amp; &quot;, &quot; &amp; TEXT(State__c) &amp; &quot; &quot; &amp; Zip__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <label>Family</label>
    <nameField>
        <label>FamilyName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FoodBank/classes/AddressInfoHelper.cls
public with sharing class AddressInfoHelper {

    // Update the address info for the supplied set of Family ID's
    public void updateAddressInfo(set<string> familyIDs) {
        List<Family__c> families = [SELECT AddressCombined__c
                                    FROM Family__c
                                    WHERE ID IN :familyIDs];
        Set<String> addressMD5s = new Set<String>();
        for (Family__c family : families) {     
            addressMD5s.add(EncodingUtil.convertToHex(Crypto.generateDigest('MD5', Blob.valueOf(family.AddressCombined__c))));
        }
    }
}