FoodBank/objects/Family__c.object
<CustomObject>
    <description>Our families</description>
    <label>Family</label>
    <nameField>
        <label>FamilyName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FoodBank/objects/Person__c.object
<CustomObject>
    <description>Family/Group members</description>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/classes/HeadOfHouseholdFetcherTestClass.cls
@isTest 
private class HeadOfHouseholdFetcherTestClass {
    static testMethod void testDefaultConstructor() {

        HeadOfHouseholdFetcher fetcher = new HeadOfHouseholdFetcher();
    }

    static testMethod void testFetchOne() {

        Family__c family = new Family__c(Name='XXX');
        insert family;
        
        Person__c person = new Person__c(Family__c=family.Id);
        insert person;
        
        HeadOfHouseholdFetcher.fetchSingle(family.ID);
    }
}