FoodBank/objects/Family__c.object
<CustomObject>
    <description>Our families</description>
    <fields>
        <fullName>AddressCombined__c</fullName>
        <description>The combined address of the family</description>
        <formula>IF(ISBLANK(AptNum__c), 
StreetNum__c &amp; &quot; &quot; &amp; StreetName__c &amp; &quot;, &quot; &amp; City__c &amp; &quot;, &quot; &amp; TEXT(State__c) &amp; &quot; &quot; &amp; Zip__c,
StreetNum__c &amp; &quot; &quot; &amp; StreetName__c &amp; &quot; Apt #&quot; &amp; AptNum__c &amp; &quot;, &quot; &amp; City__c &amp; &quot;, &quot; &amp; TEXT(State__c) &amp; &quot; &quot; &amp; Zip__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumPeople__c</fullName>
        <label>NumPeople</label>
        <summaryForeignKey>Person__c.Family__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SpecialNeeds__c</fullName>
        <label>Special Needs</label>
        <type>TextArea</type>
    </fields>
    <label>Family</label>
    <nameField>
        <label>FamilyName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FoodBank/objects/Person__c.object
<CustomObject>
    <description>Family/Group members</description>
    <fields>
        <fullName>Age__c</fullName>
        <description>The person&apos;s age</description>
        <formula>YEAR(DATEVALUE(NOW()))-YEAR( DOB__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ClothingSize__c</fullName>
        <label>Clothing Size</label>
        <picklist>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S/NC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <description>Date of birth</description>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Guest__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Guest</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <label>Relationship</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/objects/Phone__c.object
<CustomObject>
    <description>A family telephone number</description>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Phones</relationshipLabel>
        <relationshipName>Phones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Phone</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/objects/Service__c.object
<CustomObject>
    <description>A service provided to a family</description>
    <fields>
        <fullName>Adopted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Adopted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BoxSize__c</fullName>
        <label>Box Size</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S/NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S/WC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XXL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BoxType__c</fullName>
        <label>Box Type</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Supplement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compl/Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eggs only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EHP Adpt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Harvest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pack the Bag</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Produce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sandwhiches</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Snacks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youth Summer Feeding Program</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DistributionMethod__c</fullName>
        <label>Distribution Method</label>
        <picklist>
            <picklistValues>
                <fullName>Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mailed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pickup</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TypeOfMeat__c</fullName>
        <label>Type of meat</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Turkey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chicken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turkey/Ham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ham/Chicken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/classes/HolidayGiveawayController.cls
public class HolidayGiveawayController {
 
  private class PhoneInfo {
    public String phone_number {get; set;}
    public String type {get; set;}
    public String notes {get; set;}
  }

  public boolean show_header {get; set;}
  public String render_as {get; set;}
 
  public Service__c service {get; set;}
  public List<PhoneInfo> phones {get; set;}
  public List<Person__c> people {get; set;}
  public Person__c head {get; set;}

  private void getReportData(Id service_id) {
    if (service_id == null)
      return;
    service = [SELECT id, BoxType__c, BoxSize__c, TypeOfMeat__c, Adopted__c ,DistributionMethod__c,
        TimeSlot__r.DateTime__c,
        Family__r.Name, Family__r.id, Family__r.AddressCombined__c, Family__r.SpecialNeeds__c,
                Family__r.NumPeople__c, Family__r.Phone__c, Family__r.Phone_Type__c, Family__r.Phone_Notes__c
        FROM Service__c
        WHERE id = :service_id];
    phones = new List<PhoneInfo>();
    PhoneInfo phone = new PhoneInfo();
    phone.phone_number = service.Family__r.Phone__c;
    phone.type = service.Family__r.Phone_Type__c;
    phone.notes = service.Family__r.Phone_Notes__c;
    phones.add(phone);
    people = [SELECT FirstName__c, LastName__c, Gender__c, DOB__c, Age__c, Relationship__c, Guest__c, ClothingSize__c
        FROM Person__c
        WHERE Family__r.id = :service.Family__r.id];
    head = HeadOfHouseholdFetcher.fetchSingle(service.Family__r.id);
  }

  public HolidayGiveawayController() {
    render_as = '';
    show_header = true;
    Map<String, String> params = ApexPages.currentPage().getParameters();
    Id service_id = null;
    if (params.containsKey('id')) {
        service_id = Id.valueof(params.get('id'));
    }
    getReportData(service_id);
  }
  
  // Dummy action to refresh the page.
  public PageReference makePrintable() {
    return null;
  }
}