FoodBank/objects/Family__c.object
<CustomObject>
    <description>Our families</description>
    <label>Family</label>
    <nameField>
        <label>FamilyName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FoodBank/objects/Person__c.object
<CustomObject>
    <description>Family/Group members</description>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <label>Relationship</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/classes/HeadOfHouseholdFetcher.cls
public class HeadOfHouseholdFetcher {
  
  public static Map<Id, String> fetch(Set<Id> family_ids) {
    List<Person__c> people = [SELECT FirstName__c, LastName__c, Relationship__c, Person__c.Family__r.id
        FROM Person__c
        WHERE Person__c.Family__r.id in :family_ids];
    Map<Id, String> heads = new Map<Id, String>();
    for (Id i : family_ids) {
      heads.put(i, '');
    }
    for (Person__c p : people) {
      Id family_id = p.Family__r.id;
      String entry = heads.get(family_id);
      if (String.isBlank(entry) || p.Relationship__c == 'HEAD') {
        heads.put(family_id, p.FirstName__c + ' ' + p.LastName__c);
      }
    }
    return heads;
  }
}