FoodBank/objects/Service__c.object
<CustomObject>
    <description>A service provided to a family</description>
    <label>Service</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FoodBank/objects/TimeSlot__c.object
<CustomObject>
    <fields>
        <fullName>Allocated__c</fullName>
        <description>The number of slots already allocated (scheduled) for various services.</description>
        <inlineHelpText>This field is automatically calculated.</inlineHelpText>
        <label>Allocated</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>TimeSlot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TimeSlots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FoodBank/classes/TimeSlotHelper.cls
public with sharing class TimeSlotHelper {

    // Update the allocated counts for the supplied set of TimeSlot ID's
    public void updateAllocatedCount(set<string> timeslotIDs) {
         
        if(timeslotIDs == null || timeslotIDs.isEmpty()){   
            return;
        }
        
        // First sum up all timeslots in use by any service
        list<Service__c> serviceIDs = new list<Service__c>();
        serviceIDs = [Select TimeSlot__c
                    From Service__c
                    Where TimeSlot__c = :timeslotIDS];

        integer totalCount;
        map<string, integer> timeSlotIDToCountMap = new map<string, integer>();       
        for (Service__c serviceItem : serviceIDs) {
            if (timeSlotIDToCountMap.containsKey(serviceItem.TimeSlot__c))
                totalCount = timeSlotIDToCountMap.get(serviceItem.TimeSlot__c);
            else
                totalCount = 0;
            totalCount++;
            timeSlotIDToCountMap.put(serviceItem.TimeSlot__c, totalCount);
        }
        
        // Now update the allocated field in the TimeSlot object
        list<TimeSlot__c> slotUpdateList = new list<TimeSlot__c>();
        TimeSlot__c slotTemp;
        for(string slotID : timeSlotIDToCountMap.keySet()) {
            if (String.isEmpty(slotID))
                continue;
            slotTemp = new TimeSlot__c();
            slotTemp.ID = slotID;
            slotTemp.Allocated__c = timeSlotIDToCountMap.get(slotID);
            slotUpdateList.add(slotTemp);
        }
        if(!slotUpdateList.isEmpty()) {
            update slotUpdateList;
        }
    }
}